"""Add status field to Registration

Revision ID: d73d2a4e55a8
Revises: ec1ccd14271f
Create Date: 2025-03-22 17:35:09.850942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73d2a4e55a8'
down_revision = 'ec1ccd14271f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 