"""Add tablename attributes

Revision ID: ec1ccd14271f
Revises: 054579040c26
Create Date: 2025-03-20 04:23:45.403437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec1ccd14271f'
down_revision = '054579040c26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_registrations_qr_code', table_name='registrations')
    op.drop_index('idx_registrations_ticket_number', table_name='registrations')
    op.drop_constraint('registrations_user_id_event_id_key', 'registrations', type_='unique')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('registrations_user_id_event_id_key', 'registrations', ['user_id', 'event_id'])
    op.create_index('idx_registrations_ticket_number', 'registrations', ['ticket_number'], unique=False)
    op.create_index('idx_registrations_qr_code', 'registrations', ['qr_code_uuid'], unique=False)
    # ### end Alembic commands ### 