"""Add status field to Registration

Revision ID: f490f8fe6aa6
Revises: d73d2a4e55a8
Create Date: 2025-03-22 17:37:25.789105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f490f8fe6aa6'
down_revision = 'd73d2a4e55a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registrations', sa.Column('status', sa.String(length=20), server_default='registered', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'status')
    # ### end Alembic commands ### 